branches:
  only:
    - develop

os: linux
dist: focal
language: cpp

git:
  depth:
    3

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "$(git log -1 --pretty=format:'%aE')"  # TODO: switch author email back to: "lxpugin@gmail.com" if necessary
    - SHA: "$(git rev-parse --verify HEAD)"
    # repos
    - VEROVIO_REPOSITORY: "https://${GH_TOKEN}@github.com/rism-ch/verovio"
    # branches
    - BUILD_BRANCH: develop

# define order of stages
# conditions for any stage can be included here
stages:
  - deploy

jobs:
  include:
    ##############
    # DEPLOY stage
    ##############
    # deploys toolkit and doxygen builds in parallel
    - stage: deploy
      name: doxygen
      os: linux
      addons:
        apt:
          packages:
            - doxygen
      script:
        - ./travis/ci_deploy-doxygen.sh
