name: Python Build v2

on:
  push:
    # Trigger the workflow on push,
    # but only for the branches specified
    branches:
      # Push events on develop branch
      - develop-wheel-no

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9] # this can be changed by the user
        os: [macOS-latest, ubuntu-latest] # this can be changed by the user
    steps:
    - name: STEP 1. Check-Out Repo
      uses: actions/checkout@v2

    #===============================================#
    - name: Install packages
      if: matrix.os == 'windows-latest'
      run: |
        nuget install swigwintools -Version 4.0.0 -OutputDirectory .\bindings\python
        
    - name: Install packages
      if: matrix.os == 'macOS-latest'
      run: |
        brew install swig

    - name: Install packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install swig

    #===============================================#
    - name: Set-Up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    #===============================================#
    - name: STEP 3. Build Verovio
      run: |
        python -m pip install wheel
        python setup.py build_ext
        python setup.py bdist_wheel

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.python-version }}
        path: bindings/python/dist/*.whl