name: Verovio CI Build

on:
  push:
    # Trigger the workflow on push,
    # but only for the branches specified
    branches:
      # Push events on develop branch
      - develop
      # Push events on ci-test branch (only needed for testing purposes)
      - ci-test
      # Push events on travis-test branch (only needed for testing purposes)
      - travis-test

# globals
env:
  # emscripten
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: emsdk-cache

  # gh-pages
  GH_PAGES_REPO: ${{ github.repository_owner }}/verovio.org  # --> resolves to rism-ch/verovio.org
  GH_PAGES_BRANCH: gh-pages

  #doxygen
  DOXYGEN_REPO: ${{ github.repository_owner }}/verovio-doxygen
  DOXYGEN_BRANCH: master

  # build artifacts
  CLI_BUILD: cli-build
  TOOLKIT_BUILD: toolkit-build

  # temporary directories
  DOXYGEN_DIR: doxygen
  GH_PAGES_DIR: gh-pages-dir
  TEMP_DIR: temp-dir


jobs:

  ###############################################
  # Deploy the documentation to verovio-doxygen #
  ###############################################
  deploy:
    name: Deploy doxygen
    runs-on: ubuntu-20.04
    # run deployment only after finishing the build jobs
    # needs: [build_cpp, build_cli, build_js]

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Checkout DOXYGEN_REPO into DOXYGEN_DIR
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DOXYGEN_REPO }}
          ssh-key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY_DOXYGEN }}
          ref: ${{ env.DOXYGEN_BRANCH }}
          path: ${{ env.DOXYGEN_DIR }}

      - name: Install doxygen
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends doxygen

      - name: Check installation
        run: |
          doxygen --help

      - name: Build documentation
        working-directory: ${{ github.WORKSPACE }}/doc
        run: (cat verovio.conf ; echo "OUTPUT_DIRECTORY = $GITHUB_WORKSPACE/${DOXYGEN_DIR}") | doxygen -

      - name: Check files in WORKSPACE
        if: always()
        working-directory: ${{ github.WORKSPACE }}
        run: |
          pwd
          ls -al

      - name: Check files in DOXYGEN
        if: always()
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          pwd
          ls -al

      - name: Configure git
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          echo "Configuring git"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Check git status before commit
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          git config --get remote.origin.url
          git status

      - name: Commit files
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          echo "Running git commit"
          git add .
          git commit -m "Auto-commit of documentation build for ${{ github.repository }}@${{ github.sha }}"

      - name: Check git status after commit
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          git config --get remote.origin.url
          git status

      - name: Push changes to doxygen
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          # Push all changes in one commit to the doxygen repo
          echo "Build branch ready to go. Pushing to Github..."

          git push -v --dry-run origin HEAD:$DOXYGEN_BRANCH

      - name: Congratulations
        if: ${{ success() }}
        run: |
          echo "🎉 Documentation deployed 🎊"
