name: Verovio CI Build

on:
  push:
    # Trigger the workflow on push,
    # but only for the branches specified
    branches:
      # Push events on develop branch
      - develop
      # Push events on ci-test branch (uncomment if needed for testing purposes)
      - '**'

# globals
env:
  # general settings
  RISM_OWNER: rism-ch

  DISABLE_DEPLOY_STEPS: true    # Flag used to disable deploy steps at all (default: true).
                                # TRUE (no matter what IS_DRY_RUN): Will skip deploy steps of the workflow.
                                # FALSE (together with IS_DRY_RUN = true): Will allow to run deploy steps in dry-run mode.
                                # FALSE (together with IS_DRY_RUN = false): Will allow to deploy/git push from fork.
                                # Will be programmatically set to 'false' for rism-ch repo.

  IS_DRY_RUN: true              # Flag used for dry-run mode in 'git push' command (default: true).
                                # TRUE (needs DISABLE_DEPLOY_STEPS = false): Will allow to run deploy steps in dry-run mode.
                                # FALSE (needs DISABLE_DEPLOY_STEPS = false): Will allow to deploy/git push from fork.
                                # Will be programmatically set to 'false' for rism-ch repo.

  # build artifacts
  CLI_BUILD: cli-build
  DOC_BUILD: doc-build
  TOOLKIT_BUILD: toolkit-build

  # doxygen
  DOXYGEN_REPO: ${{ github.repository_owner }}/verovio-doxygen # works from rism-ch and from forks
  DOXYGEN_BRANCH: master

  # emscripten
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: emsdk-cache

  # gh-pages
  GH_PAGES_REPO: ${{ github.repository_owner }}/verovio.org  # works from rism-ch and from forks
  GH_PAGES_BRANCH: gh-pages

  # temporary directories
  DOXYGEN_DIR: doxygen-dir
  GH_PAGES_DIR: gh-pages-dir
  TEMP_DIR: temp-dir


jobs:

  ###########################
  # Build test artifact #
  ###########################
  build_cli:
    name: Build cli
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Create temp dir
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p $TEMP_DIR/

      - name: Update cli.txt
        working-directory: ${{ github.workspace }}/$TEMP_DIR
        run: |
          touch cli.txt
          echo "Test" > cli.txt

      - name: Upload cli artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CLI_BUILD }}
          path: ${{ github.workspace }}/${{ env.TEMP_DIR }}/cli.txt

      - name: Check files
        if: always()
        working-directory: ${{ github.workspace }}/${{ env.TEMP_DIR }}
        run: |
          pwd
          ls -al


  ####################################
  # Prepare deploy steps for RISM_CH #
  ####################################
  prepare_deploy:
    name: Prepare deployment steps for rism-ch
    runs-on: ubuntu-20.04
    # run deployment only after finishing the build jobs
    # needs: [ build_cpp, build_cli, build_js ]
    needs: [ build_cli ]

    steps:
      - name: Prepare deployment for rism-ch
        if: ${{ github.repository_owner == env.RISM_OWNER }}
        run: |
          echo "Enable deploy steps on rism-ch..."
          echo "DISABLE_DEPLOY_STEPS=false" >> $GITHUB_ENV

          echo "Disabling dry-run mode on rism-ch..."
          echo "IS_DRY_RUN=false" >> $GITHUB_ENV

      - name: Check deployment settings
        run: |
          echo "DISABLE_DEPLOY_STEPS = ${DISABLE_DEPLOY_STEPS}"
          echo "IS_DRY_RUN = ${IS_DRY_RUN}"

  #########################################
  # Deploy the toolkit builds to gh-pages #
  #########################################
  deploy_toolkit:
    name: Deploy JS toolkit
    runs-on: ubuntu-20.04
    # run deployment only after finishing the build jobs
    # needs: [build_cpp, build_cli, build_js, prepare_deploy]
    needs: [build_cli, prepare_deploy]

    steps:
      - name: Checkout GH_PAGES_REPO into GH_PAGES_DIR
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_PAGES_REPO }}
          ssh-key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY }}
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_DIR }}

      - name: Download CLI_BUILD artifacts
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CLI_BUILD }}
          path: artifacts/${{ env.CLI_BUILD }}

#      - name: Download TOOLKIT_BUILD artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: ${{ env.TOOLKIT_BUILD }}
#          path: artifacts/${{ env.TOOLKIT_BUILD }}

      - name: Copy artifacts to gh-pages
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        run: |
          cp artifacts/$CLI_BUILD/cli.txt $GH_PAGES_DIR/_includes/
          # cp artifacts/$TOOLKIT_BUILD/* $GH_PAGES_DIR/javascript/develop/

      - name: Check git status before commit
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        working-directory: ${{ env.GH_PAGES_DIR }}
        run: |
          git config --get remote.origin.url
          git status

      - name: Configure git
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        working-directory: ${{ env.GH_PAGES_DIR }}
        run: |
          echo "Configuring git"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Commit files
        if: ${{ DISABLE_DEPLOY_STEPS == 'false' }}
        working-directory: ${{ env.GH_PAGES_DIR }}
        run: |
          echo "Running git commit"
          git add .
          git commit -m "Auto-commit of toolkit build for ${{ github.repository }}@${{ github.sha }}"

      #      - name: Check git status after commit
      #        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
      #        working-directory: ${{ env.GH_PAGES_DIR }}
      #        run: |
      #          git config --get remote.origin.url
      #          git status

      - name: Push changes to gh-pages (dry-run)
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' && env.IS_DRY_RUN == 'true' }}
        working-directory: ${{ env.GH_PAGES_DIR }}
        run: |
          # Push all changes in one commit to the gh-pages repo
          echo "Build branch ready to go."

          echo "Running git in dry-run mode..."
          git push -v --dry-run origin HEAD:$GH_PAGES_BRANCH

      - name: Push changes to gh-pages
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' && env.IS_DRY_RUN == 'false' }}
        working-directory: ${{ env.GH_PAGES_DIR }}
        run: |
          # Push all changes in one commit to the gh-pages repo
          echo "Build branch ready to go."

          echo "Pushing to Github..."
          git push origin HEAD:$GH_PAGES_BRANCH

      - name: Congratulations
        if: ${{ success() && env.DISABLE_DEPLOY_STEPS == 'false' }}
        run: |
          echo "🎉 New JS toolkit builds deployed 🎊"

      - name: Skipped
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'true' }}
        run: |
          echo "Deploy job skipped"


  ###################################
  # Build the doxygen documentation #
  ###################################
  build_docs:
    name: Build documentation
    runs-on: ubuntu-20.04
    # run only after finishing other build jobs
    needs: [build_cpp, build_cli, build_js]

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Install doxygen
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends doxygen

      - name: Check installation
        run: |
          doxygen --help

      - name: Upgrade doxygen conf
        working-directory: ${{ github.workspace }}/doc
        run: doxygen -u verovio.conf

      - name: Build documentation with (updated) doxygen conf
        working-directory: ${{ github.workspace }}/doc
        if: ${{ success() }}
        run: (cat verovio.conf ; echo "OUTPUT_DIRECTORY = $GITHUB_WORKSPACE/$DOXYGEN_DIR") | doxygen -

      - name: Upload doxygen build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DOC_BUILD }}
          path: ${{ github.workspace }}/${{ env.DOXYGEN_DIR }}

      - name: Check files
        working-directory: ${{ github.WORKSPACE }}/${{ env.DOXYGEN_DIR }}
        if: always()
        run: |
          pwd
          ls -al
          ls -R


  ###############################################
  # Deploy the documentation to verovio-doxygen #
  ###############################################
  deploy_docs:
    name: Deploy documentation
    runs-on: ubuntu-20.04
    # run deployment only after finishing the build job
    needs: [build_docs, prepare_deploy]

    steps:
      - name: Checkout DOXYGEN_REPO into DOXYGEN_DIR
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DOXYGEN_REPO }}
          ssh-key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY_DOXYGEN }}
          ref: ${{ env.DOXYGEN_BRANCH }}
          path: ${{ env.DOXYGEN_DIR }}

      - name: Download DOC_BUILD artifacts
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.DOC_BUILD }}
          path: artifacts/${{ env.DOC_BUILD }}

      - name: Copy build artifacts to DOXYGEN_DIR
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        run: |
          cp -a artifacts/$DOC_BUILD/* $DOXYGEN_DIR/

      - name: Check git status before commit
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          git config --get remote.origin.url
          git status

      - name: Configure git
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          echo "Configuring git..."
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Commit files
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' }}
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          echo "Running git commit..."
          git add .
          git commit -m "Auto-commit of documentation build for ${{ github.repository }}@${{ github.sha }}"

      #      - name: Check git status after commit
      #        working-directory: ${{ env.DOXYGEN_DIR }}
      #        run: |
      #          git config --get remote.origin.url
      #          git status

      - name: Push changes to doxygen (dry-run)
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' && env.IS_DRY_RUN == 'true' }}
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          # Push all changes in one commit to the doxygen repo
          echo "Build branch ready to go."

          echo "Running git in dry-run mode..."
          git push -v --dry-run origin HEAD:$DOXYGEN_BRANCH


      - name: Push changes to doxygen
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'false' && env.IS_DRY_RUN == 'false' }}
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          # Push all changes in one commit to the doxygen repo
          echo "Build branch ready to go."

          echo "Pushing to Github..."
          git push origin HEAD:$DOXYGEN_BRANCH

      - name: Congratulations
        if: ${{ success() && env.DISABLE_DEPLOY_STEPS == 'false' }}
        run: |
          echo "🎉 New documentation deployed 🎊"

      - name: Skipped
        if: ${{ env.DISABLE_DEPLOY_STEPS == 'true' }}
        run: |
          echo "Deploy job skipped"
