name: Verovio CI Build

on:
  push:
    # Trigger the workflow on push,
    # but only for the branches specified
    branches:
      # Push events on develop branch
      - develop
      # Push events on ci-test branch (only needed for testing purposes)
      - ci-test
      # Push events on travis-test branch (only needed for testing purposes)
      - travis-test

# globals
env:
  RISM_OWNER: rism-ch

  # build artifacts
  CLI_BUILD: cli-build
  DOC_BUILD: doc-build
  TOOLKIT_BUILD: toolkit-build

  # doxygen
  DOXYGEN_REPO: ${{ github.repository_owner }}/verovio-doxygen # works also for forks of verovio
  DOXYGEN_BRANCH: master

  # emscripten
  EMSCRIPTEN_VERSION: latest
  EMSCRIPTEN_CACHE_FOLDER: emsdk-cache

  # gh-pages
  GH_PAGES_REPO: ${{ github.repository_owner }}/verovio.org # works also for forks of verovio
  GH_PAGES_BRANCH: gh-pages

  # temporary directories
  DOXYGEN_DIR: doxygen-dir
  GH_PAGES_DIR: gh-pages-dir
  TEMP_DIR: temp-dir

  IS_DRY_RUN: false


jobs:

  ###############################################
  # Deploy the documentation to verovio-doxygen #
  ###############################################
  deploy_docs:
    name: Deploy documentation
    runs-on: ubuntu-20.04
    # run deployment only after finishing the build jobs

    steps:
      - name: Checkout DOXYGEN_REPO into DOXYGEN_DIR
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DOXYGEN_REPO }}
          ssh-key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY_DOXYGEN }}
          ref: ${{ env.DOXYGEN_BRANCH }}
          path: ${{ env.DOXYGEN_DIR }}

      - name: Create file for DOXYGEN_DIR
        run: |
          touch testfile.txt
          cp testfile.txt $DOXYGEN_DIR/

      - name: Check git status before commit
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          git config --get remote.origin.url
          git status

      - name: Configure git
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          echo "Configuring git"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Commit files
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |
          echo "Running git commit"
          git add .
          git commit -m "Auto-commit of documentation build for ${{ github.repository }}@${{ github.sha }}"

#      - name: Check git status after commit
#        working-directory: ${{ env.DOXYGEN_DIR }}
#        run: |
#          git config --get remote.origin.url
#          git status

      - name: Configure dry-run
        if: github.repository_owner != env.RISM_OWNER
        run: |
          echo "**********"
          echo $GITHUB_ENV

          echo "-----------------"
          echo "Configure dry-run"
          echo "{DRY_RUN_OPTION}={$(echo '-v --dry-run')}" >> $GITHUB_ENV
          echo "{IS_DRY_RUN}={true}" >> $GITHUB_ENV


      - name: Push changes to doxygen
        working-directory: ${{ env.DOXYGEN_DIR }}
        run: |

          echo "**********"
          echo $GITHUB_ENV

          echo "-----------------"
          echo $DRY_RUN_OPTIONS



          # Push all changes in one commit to the doxygen repo
          echo "Build branch ready to go. Pushing to Github..."

          if [ "$IS_DRY_RUN" = true ]
          then
            echo "Push dry-run style"
            git push -v --dry-run origin HEAD:$DOXYGEN_BRANCH
          else
            echo "Real push to repo"
            # git push origin HEAD:$DOXYGEN_BRANCH
          fi

          # git push $IS_DRY_RUN origin HEAD:$DOXYGEN_BRANCH

      - name: Congratulations
        if: ${{ success() }}
        run: |
          echo "🎉 Documentation deployed 🎊"
