name: Python Build

on:
  workflow_dispatch: # manual trigger
  push:
    # Trigger the workflow on push,
    # but only for the branches specified
    branches:
      # Push events on develop branch
      - ci-test


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: [3.7] # [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
     
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine # cibuildwheel==1.7.1
      
      #- name: Install cibuildwheel
      #  run: |
      #     python -m pip install cibuildwheel==1.7.1
      
      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y
      
      - name: Build wheels
        env:
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp* cp27-* cp35-* cp39-*"

          CIBW_BEFORE_BUILD_WINDOWS: nuget install swigwintools -Version 4.0.0 -OutputDirectory C:\\cibw
          CIBW_BEFORE_BUILD_LINUX: yum install swig
          CIBW_BEFORE_BUILD_MACOS: brew install swig
        run: |
          cd bindings/python
          python -m cibuildwheel --output-dir wheelhouse
      
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
