name: Verovio CI Build

on:
  pull_request:
    branches: develop
  # TODO: run this task only on PR in production; use push event for testing
  #push:
    #branches:
    # - '**'

# globals
env:
  # general settings
  MAIN_REPO_OWNER: rism-ch      # Main repo owner (default: rism-ch; should not be changed)
                                # If changed, owner needs deploy permission to <owner>/verovio.org and <owner>/verovio-doxygen (cf. Deploy jobs).
                                # DISABLE_DEPLOY_STEPS & IS_DRY_RUN are programmatically set to false for main repo owner.

  DISABLE_DEPLOY_STEPS: true    # Flag used to disable deploy steps at all (default: true).
                                # TRUE (no matter what IS_DRY_RUN): Will skip deploy steps of the workflow.
                                # FALSE (together with IS_DRY_RUN = true): Will allow to run deploy steps in dry-run mode.
                                # FALSE (together with IS_DRY_RUN = false): Will allow to deploy/git push from fork.
                                # Will be programmatically set to 'false' for rism-ch repo.

  IS_DRY_RUN: true              # Flag used for dry-run mode in 'git push' command (default: true).
                                # TRUE (needs DISABLE_DEPLOY_STEPS = false): Will allow to run deploy steps in dry-run mode.
                                # FALSE (needs DISABLE_DEPLOY_STEPS = false): Will allow to deploy/git push from fork.
                                # Will be programmatically set to 'false' for rism-ch repo.

  # build artifacts
  TOOLKIT_BUILD: toolkit-build

  # gh-pages
  GH_PAGES_REPO: ${{ github.repository_owner }}/verovio.org  # works from rism-ch and from forks
  GH_PAGES_BRANCH: gh-pages

  # temporary directories
  GH_PAGES_DIR: gh-pages-dir
  TEMP_DIR: temp-dir
  PR_DIR: pr-${{ github.event.pull_request.head.sha }}
  DEV_DIR: dev-dir
  OUTPUT_DIR: output-dir

jobs:
  ###################################################
  # Build the Python toolkit and run the test suite #
  ###################################################
  build_python:
    name: Build the test suite
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_DIR
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_PAGES_REPO }}
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_DIR }}

      - name: Create temp directories and install packages
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p $TEMP_DIR/$DEV_DIR/
          mkdir -p $TEMP_DIR/$PR_DIR/
          mkdir -p $TEMP_DIR/$OUTPUT_DIR/
          sudo apt-get install librsvg2-bin
          rsvg-convert --version

      - name: Checkout the dev branch
        uses: actions/checkout@v2
        with:
          ref: develop
          path: $DEV_DIR/

      - name: Build Python toolkit and run the tests for the dev branch
        working-directory: ${{ github.workspace }}/$DEV_DIR/bindings/python
        run: |
          python3 setup.py build_ext --inplace
          python3 ../../doc/test-suite.py ${{ github.workspace }}/${{env.GH_PAGES_DIR}}/_tests ${{ github.workspace }}/$TEMP_DIR/$DEV_DIR/
          ../../doc/test-suite-to-png.sh ${{ github.workspace }}/$TEMP_DIR/$DEV_DIR/

      - name: Checkout the PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: $PR_DIR/

      - name: Build Python toolkit and run the tests for the PR
        working-directory: ${{ github.workspace }}/$PR_DIR/bindings/python
        run: |
          python3 setup.py build_ext --inplace
          python3 ../../doc/test-suite.py ${{ github.workspace }}/${{env.GH_PAGES_DIR}}/_tests ${{ github.workspace }}/$TEMP_DIR/$PR_DIR/
          ../../doc/test-suite-to-png.sh ${{ github.workspace }}/$TEMP_DIR/$PR_DIR/

      - name: Compare the tests
        working-directory: ${{ github.workspace }}/$DEV_DIR/doc
        run: |
          python3 ./test-suite-diff.py ${{ github.workspace }}/$TEMP_DIR/$PR_DIR/ ${{ github.workspace }}/$TEMP_DIR/$DEV_DIR/ ${{ github.workspace }}/$TEMP_DIR/$OUT_DIR/
          ls -al

      

