name: Verovio CI Test Suite

on:
  # pull_request:
  #  branches: develop
  # TODO: run this task only on PR in production; use push event for testing
  push:
    branches:
      - '**'

# globals
env:
  # gh-pages
  GH_PAGES_REPO: ${{ github.repository_owner }}/verovio.org
  GH_PAGES_BRANCH: gh-pages

  # build artifacts
  TEST_BUILD: test-build

  # temporary directories
  GH_PAGES_DIR: gh-pages
  TEMP_DIR: temp


jobs:
  test:
    name: Run Verovio test suite
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_DIR
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_PAGES_REPO }}
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_DIR }}

      - name: Verify
        run: |
          pwd
          ls -al
          ls -R

      - name: Find tests
        env:
          TEST_DIR: ${{ github.workspace }}/${{env.GH_PAGES_DIR}}/_tests
        working-directory: ${{ env.TEST_DIR }}
        run: |
          pwd
          ls -al

          for testcategory in $TEST_DIR/*; do
            if [ "$testcategory" = "*" ]; then continue; fi   # skip empty directory
            if [ -d "$testcategory" ]; then
              echo "********"
              echo $testcategory

              if [ "$testcategory" == "$TEST_DIR/ligature" ]
              then
                echo "Found ligature"
                continue
              fi

              for testfile in $testcategory/*.mei; do echo $testfile; done
            else
              echo "### No test file here..."
            fi

          done

      # Cache verovio build
      - name: Set up cache
        id: cache
        uses: actions/cache@v2
        with:
          # path for cache
          path: ${{ github.workspace }}/tools/verovio
          # key for cache
          key: ${{ runner.os }}-verovio-build-${{ github.sha }}

      # if no cache is found, build verovio
      - name: Run make
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/tools
        run: |
          cmake ../cmake
          make -j8

      - name: Create temp dir
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p $TEMP_DIR/

      # run the test suite
      - name: Run tests
        env:
          TEST_DIR: ${{ github.workspace }}/${{env.GH_PAGES_DIR}}/_tests
        working-directory: ${{ github.workspace }}/tools
        run: |
          for testcategory in $TEST_DIR/*; do
            # skip empty directory
            if [ "$testcategory" = "*" ]; then continue; fi

            if [ -d "$testcategory" ]; then
              echo "********"
              echo $testcategory

              echo "* Creating SVG files..."
              for testfile in $testcategory/*.mei; do
                if [ -f "$testfile" ]; then
                  echo "--"
                  echo $testfile

                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-001.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-002.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-003.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-004.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-005.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-006.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-007.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-008.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-009.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-010.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-011.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-012.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-013.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-014.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-015.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-016.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-017.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-018.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-019.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-020.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-021.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-022.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-023.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-024.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-025.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-026.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-027.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-028.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-029.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-030.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-031.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-032.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-033.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-034.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-035.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-036.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-037.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-038.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-039.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-040.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-041.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-042.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-043.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-044.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-045.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-046.mei" ]; then continue; fi


                  if [ "$testfile" == "$TEST_DIR/mensural/mensural-001.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/note/note-003.mei" ]; then continue; fi
                  # if [ "$testfile" == "$TEST_DIR/sameas/sameas-002.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/stem/stem-002.mei" ]; then continue; fi

                  ./verovio -r ../data/ $testfile --breaks none --adjust-page-height --scale 50

                else
                  echo "### No test file here..."
                fi
              done

              echo "* Creating MEI files..."
              for testfile in $testcategory/*.mei; do
                if [ -f "$testfile" ]; then
                  echo "--"
                  echo $testfile

                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-001.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-002.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-003.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-004.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-005.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-006.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-007.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-008.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-009.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-010.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-011.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-012.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-013.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-014.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-015.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-016.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-017.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-018.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-019.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-020.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-021.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-022.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-023.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-024.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-025.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-026.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-027.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-028.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-029.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-030.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-031.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-032.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-033.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-034.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-035.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-036.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-037.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-038.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-039.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-040.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-041.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-042.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-043.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-044.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-045.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/ligature/ligature-046.mei" ]; then continue; fi


                  if [ "$testfile" == "$TEST_DIR/mensural/mensural-001.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/note/note-003.mei" ]; then continue; fi
                  # if [ "$testfile" == "$TEST_DIR/sameas/sameas-002.mei" ]; then continue; fi
                  if [ "$testfile" == "$TEST_DIR/stem/stem-002.mei" ]; then continue; fi

                  ./verovio -r ../data/ -t mei --remove-ids --all-pages $testfile

                else
                  echo "### No test file here..."
                fi
              done

              echo "* Copying SVG files..."
              count=`ls -1 $testcategory/*.svg 2>/dev/null | wc -l`
              if [ "$count" != 0 ]; then
                mv $testcategory/*.svg $GITHUB_WORKSPACE/$TEMP_DIR;
              else
                echo "### No svg output to copy here..."
              fi
            else
              echo "### No test category here..."
            fi
          done

      - name: Verify
        working-directory: ${{ github.WORKSPACE }}/${{ env.TEMP_DIR }}
        run: |
          pwd
          ls -al

