name: Verovio CI Test Suite

on:
  # pull_request:
  #  branches: develop
  # TODO: run this task only on PR in production; use push event for testing
  push:
    branches:
      - '**'

# globals
env:
  # gh-pages
  GH_PAGES_REPO: rism-ch/verovio.org
  GH_PAGES_BRANCH: gh-pages
  GH_PAGES_FOLDER: gh-pages

  # build artifacts
  TEST_BUILD: test-build

  # temp
  TEMP_FOLDER: temp


jobs:
  test:
    name: Run Verovio test suite
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Checkout GH_PAGES_BRANCH into GH_PAGES_FOLDER
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_PAGES_REPO }}
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: ${{ env.GH_PAGES_FOLDER }}

      - name: Verify
        run: |
          pwd
          ls -al
          ls -R

      - name: Find tests
        run: |
          cd $GITHUB_WORKSPACE/$GH_PAGES_FOLDER/_tests
          ls -al

      - name: Run make
        run: |
          cd $GITHUB_WORKSPACE/tools
          cmake ../cmake
          make -j 8

      - name: Run tests
        env:
          TEST_DIR: ${{ github.workspace }}/${{env.GH_PAGES_FOLDER}}/_tests
        run: |
          mkdir -p $GITHUB_WORKSPACE/$TEMP_FOLDER

          cd $GITHUB_WORKSPACE/tools
          for t in $TEST_DIR/*; do
              for i in $TEST_DIR/$t/*.mei; do ./verovio -r ../data/ $i --breaks none --adjust-page-height --scale 50; done
              for i in $TEST_DIR/$t/*.mei; do ./verovio -r ../data/ -t mei --remove-ids --all-pages $i; done
              mv $TEST_DIR/$t/*.svg $GITHUB_WORKSPACE/$TEMP_FOLDER;
          done

      - name: Verify
        run: |
          cd $GITHUB_WORKSPACE/$TEMP_FOLDER
          pwd
          ls -al

